### ISSUE TITLE
Add human-readable error for db_backup script if PostgreSQL client not installed

### ISSUE THREAD

**Issue by noahddewitt** [TriticeaeToolbox/breedbase#1]
If a client package is not installed, script will attempt to run the pg_dump command with an the $PG_DUMP bin path as an empty string, and generate an empty sql file as a backup. 

Maybe something like -- 

\# Check PostgreSQL client installed
if [ -z "$PG_DUMP" ]; then
   echo "ERROR: pg_dump command not found"
   echo "Perhaps try 'apt-get/yum install postgresql-client'?"
   exit
fi

?

**Comment by dwaring87** [comment]
Thanks for pointing this out - it would be good to check if the commands are available first.
