### ISSUE TITLE
Recorded 0s for CO wheat traits not imported

### ISSUE THREAD

**Issue by noahddewitt** [TriticeaeToolbox/breedbase#4]
On importing data into Breedbase on traits from the CO wheat list (in this case, Stripe rust plant response - 0-9 Mc Neal scale|CO_321:0001394 and Agronomic Merit - 1-9 Agronomic Merit Rating|CO_321:0501170), 0 values for traits are recorded as "NA"s. This occurs when both importing the trait and trial from T3 breedbase, recording the data, then exporting back to the database through BrAPI. This also occurs when creating a phenotype spreadsheet through the trial page, filling in the spreadsheet manually, and uploading through the trial page. In both cases clicking on the page associated with the plot shows no phenotype data as having been recorded.

**Comment by noahddewitt** [comment]
It looks like this is specifically an issue with the phenotype heatmap view. Zero values are stored appropriately and can be exported, but show up as "NAs" in the phenotype heatmap view (hovering over plots displays "trait value: _NA_")

**Comment by noahddewitt** [comment]
Seems to also be an issue with the "Phenotype raw data" view, where observations with zero values are treated as if they do not exist :

![image](https://github.com/TriticeaeToolbox/breedbase/assets/82885768/fef1fe44-2255-4a41-96ec-437073c01d48)

Searching for the name of an observationunit (plot) with a non-zero recorded value filters this table for that plot. Searching the name of a observationunit with a zero value returns an empty table.

**Comment by dwaring87** [comment]
Thanks for reporting this.  This is probably due to perl treating both `0` and `undef` as false in if statements that are checking if trait values exist.  We should be able to explicitly check for 0 values, it's just a matter of finding in the code where that should be added.

**Comment by noahddewitt** [comment]
Makes sense. Thanks for working on it! I've found the heatmap feature to be very useful for quickly validating data and looking at field trends.

**Comment by dwaring87** [comment]
This will be fixed by https://github.com/solgenomics/sgn/pull/4853

This fixes the BrAPI endpoint that was filtering out 0s, which in turn fixed both the phenotype heatmap and the raw values table (since they both use BrAPI).  There might be other places that aren't using the BrAPI call that could still be filtering out 0s -- let me know if you come across any of these.
