### ISSUE TITLE
"Directly record phenotypes to database for this trial." not functional

### ISSUE THREAD

**Issue by noahddewitt** [TriticeaeToolbox/breedbase#5]
On selecting "Directly record phenotypes to database for this trial." from a trial page, are taken to a view for manually submitting single data points. Breedbase loads the accession name for the first plot correctly, but does not list any of the recorded traits. On selecting another plot, a pop-up displays with the message:

![image](https://github.com/TriticeaeToolbox/breedbase/assets/82885768/2ebeb6f4-c820-439c-bac3-801e86dfdc8c)

This message appears each subsequent time a new plot is selected. Selecting "use trait list" seems to break the view a bit:

![image](https://github.com/TriticeaeToolbox/breedbase/assets/82885768/d538ab59-0b16-4d95-9830-d602c13dc2f1)

**Comment by noahddewitt** [comment]
I don't believe this is related to #4, as it occurs in all trials and traits, with and without 0 values recorded for traits.

**Comment by dwaring87** [comment]
This is a little-used page that hasn't received much attention for a while.  There's a ticket open to fix it and add some new features to it (like an integrated barcode reader).  I didn't know there was a link to it from the trial page.

https://github.com/solgenomics/sgn/issues/4812

**Comment by dwaring87** [comment]
I'll close this for now, since it's ticketed in the sgn repo
