### ISSUE TITLE
Date phenotype stored in two separate formats

### ISSUE THREAD

**Issue by noahddewitt** [TriticeaeToolbox/breedbase#6]
For Heading Date (CO_321:0001235), data seems to be stored apparently randomly as either a datetime string or a julian day of the year. Looking at the train in fieldbook imported via BrAPI from the breedbase instance:

![Screenshot_20240321-142343](https://github.com/TriticeaeToolbox/breedbase/assets/82885768/f2a8b9a2-9617-4d60-9d03-c6d957cc0587)

All observations appear in "collect" phenotype the same way (eg "Mar 20", "Mar 25"). Export to breedbase occurs without issue. In breedbase, some observations display as a date string (2024-03-25) or as a julian day of the year (84):

![image](https://github.com/TriticeaeToolbox/breedbase/assets/82885768/9403e079-055d-4b63-ad75-712f0cb36a99)

One thing that might be going on may be that this is a trial where we are collecting data over multiple days, and often "correct" predictions of heading date, so some of these observations may be overwriting previous exported observations.

**Comment by dwaring87** [comment]
This may be more of a Field Book issue than a T3/Breedbase issue.  I don't think breedbase will make any changes to the values when storing observations - it just saves the values in the database as they're provided.  Were all of these loaded through Field Book?  It could be the trait type was set to an integer for the julian day values and a date for the yyyy-mm-dd values?

**Comment by noahddewitt** [comment]
Thanks David. Yeah, they're all from a single BrAPI export (though in Breedbase it shows up as multiple uploads of the same file for whatever reason).

![image](https://github.com/TriticeaeToolbox/breedbase/assets/82885768/1cd07bfc-56db-47f8-8cd0-4fc1b53d8111)

They're all the same in Fieldbook. I'll open an issue over on their page.

**Comment by dwaring87** [comment]
OK, that is interesting they're from the same export.  I'll try to look into it some more and see if I can replicate it.

**Comment by dwaring87** [comment]
Closing this since it seems like it's due to a change in a field book app setting
